name: 'Jupiter Toys test runner'
author: Wayne Griffiths
description: 'Runs E2E Web application tests for the Jupiter Toys Web application'
inputs:
  BASE_URL:
    description: 'Base URL for the tests'
    required: false
    default: https://jupiter.cloud.planittesting.com
  CI:
    description: 'Indiciates if this is in a CI environment, limtis parallel mode to conserve resources. A best practice measure to avoid flaky tests.'
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      shell: bash
      run: bun install

    - name: Install Playwright Browsers
      shell: bash
      run: bunx playwright install --with-deps

    - name: Run Playwright tests
      shell: bash
      run: bunx playwright test
      env:
        BASE_URL: ${{ inputs.BASE_URL }}
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
